source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'mongoid', "<=2.4.0"
gem 'mongodb'
gem 'thin'
gem 'bundler'
gem 'rake'
gem 'bson_ext'
gem 'bson'
gem 'geokit'
gem 'mongoid_spacial'
gem 'pushmeup'
gem 'bcrypt-ruby'


