source 'https://rubygems.org'

ruby '1.9.3'
gem 'sinatra'
gem 'logger'
gem 'sinatra-logger'
gem 'json'
gem 'mongoid', "<=2.4.0"
gem 'mongodb'
gem 'thin'
gem 'bundler'
gem 'rake'
gem 'bson_ext'
gem 'bson'
gem 'geokit'
gem 'mongoid_spacial'
gem 'pushmeup'
gem 'bcrypt-ruby'
gem 'rack'
gem 'haml'
gem 'regex'
gem "factory_girl", "~> 4.0"


